name: Deploy on Staging Frontend

on:
  push:
    branches: [ "Front-end" ]

jobs:
  build:
    runs-on: [self-hosted, Linux, X64, st-invochat-invo-zone]
    steps:
    - uses: actions/checkout@v3
    - name: Applying Changes
      run: |-
        cd /home/st-invochat-invo-zone/public_html/invochat-frontend
        git reset --hard
        git pull origin Front-end
        npm i
        CI=false npm run build
        pm2 reload 0
