name: Deploy on Production Frontend

on:
  push:
    branches: [ "Frontend-live" ]
  schedule: 
    - cron: '0/5 * * * *'

jobs:
  build:

    runs-on: [self-hosted, Linux, X64, invochat-io-fe-pm03]

    steps:
    - uses: actions/checkout@v3
    - name: Applying Changes
      run: |-
        cd /home/invochat-io-fe/public_html/invochat-frontend
        git reset --hard
        git pull origin Frontend-live
        npm run clean
        npm i
        npm run build
        pm2 restart 0
